# Generated by Django 4.2.1 on 2023-07-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='Priority',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-11-08'),
            preserve_default=False,
        ),
    ]
