# Generated by Django 4.2.1 on 2023-06-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='placee',
            new_name='place',
        ),
    ]
